### ISSUE TITLE
Burst of location events fired when backgroundGeolocation.start is triggered

### ISSUE THREAD

**Issue by mauron85** [mauron85/cordova-plugin-background-geolocation#112]
## Your Environment

- Plugin version: 2.1.2
- Platform: iOS, Android
- Device manufacturer and model: any
- Cordova version (`cordova -v`): 6.2.0
- Cordova platform version (`cordova platform ls`):
  -  android 5.1.1.
  -  ios ~4.1.0.
- Plugin configuration options: not relevant
- Link to your project: https://github.com/mauron85/cordova-plugin-background-geolocation
## Context

After `backgroundGeolocation.start` is called, there is burst of location due to data sampling (determining accurate initial location). However this very unpleasant as this samples have various accuracy.
## Expected Behavior

Only one best location is send instead
## Actual Behavior

Burst of location (5 on android and event more on iOS) is send instead.
## Possible Fix

Filter sample locations in plugin
## Steps to Reproduce
1. configure plugin `backgroundGeolocation.configure' with callback function
2. call `backgroundGeolocation.start`
## Context

Rendering user movement on map is mostly affected by this

**Comment by kristfal** [comment]
@mauron85 Did you do anything about this?

On iOS, I'm currently experiencing the opposite of this issue. The time for the app to receive it's first location can be anywhere from 20 to 30 seconds if the device is not moving and I'm indoors. The HTML geolocation callback takes around 3-5 seconds and provides a 'good enough' location almost instantly. 

While moving, or after initial app startup (resuming from background), location updates are very fast and behave just as expected.

I'd rather have a stream of gradually improved location updates than to wait for a 'good' location update. Is something up with my config or is this expected behavior?

### Project settings

cordova-plugin-mauron85-background-geolocation 2.2.4 /w #186 fork
iOS9 
iPhone5s
Config:
```
          desiredAccuracy: 0,
          maxLocations: 10000,
          debug: false,
          pauseLocationUpdates: false,
          locationProvider: 1,
          distanceFilterCalculationAlgorithm: 0,
          notificationText: '',
          stopOnStillActivity: false,
          startForeground: true,
          notificationTitle: this.localize('gps-is-active'),
          stationaryRadius: 5,
          distanceFilter: 10,
          interval: 1000,
          fastestInterval: 1000,
          activitiesInterval: 500,
          saveBatteryOnBackground: false,
          acitivyType: 'Fitness'
