### ISSUE TITLE
Doesn't work without internet

### ISSUE THREAD

**Issue by sonyalas10** [mauron85/cordova-plugin-background-geolocation#150]
I'm using this plugin and it works perfectly with internet and GPS but when I turn off the internet it doesn't track the location. Any ideas? I'm trying on Android
Config:
                       desiredAccuracy: 10,
            stationaryRadius: 0,
            distanceFilter: 0,
            interval: 1000,
            debug: false,
            stopOnTerminate: false,
            startOnBoot: true

document.addEventListener('deviceready', onDeviceReady, false);
    function onDeviceReady () {
    var callbackFn = function(location) {
    console.log('[js] BackgroundGeolocation callback:  ' + location.latitude + ',' + location.longitude);
    };

```
    var failureFn = function(error) {console.log('BackgroundGeolocation error');};
```

backgroundGeolocation.start();

**Comment by klidifia** [comment]
I believe if you want to do this with the existing code in the plugin you need to make use of syncUrl and syncThreshold - I've used these successfully so that without internet it will still store the locations, and then send them to the server when it can; as per the documentation. But if you're wanting to do something other than POST them to a server; this might not be what you're looking for.

**Comment by mauron85** [comment]
Notice: this issue has been closed because it has been reported for branch 2.x or later. It could be already fixed in v3 or is not relevant anymore. You may reopen this issue if it has been closed in error.
