### ISSUE TITLE
How to change interval on iOS?

### ISSUE THREAD

**Issue by MrXyfir** [mauron85/cordova-plugin-background-geolocation#393]
```js
       const INTERVAL = 600 * 1000; // 10 minutes

        window.BackgroundGeolocation.configure({
          desiredAccuracy: window.BackgroundGeolocation.HIGH_ACCURACY,
          stationaryRadius: 50,
          distanceFilter: 50,
          notificationTitle: 'Background tracking',
          notificationText: 'ENABLED',
          debug: false,
          startForeground: true,
          startOnBoot: true,
          stopOnTerminate: false,
          activityType: 'OtherNavigation',
          pauseLocationUpdates: false,
          saveBatteryOnBackground: false,
          locationProvider: window.BackgroundGeolocation.DISTANCE_FILTER_PROVIDER,
          interval: INTERVAL,
          fastestInterval: INTERVAL,
          activitiesInterval: INTERVAL
        });
```

I know the interval properties are only for Android, but is there any similar system at all for iOS? On Android the location updates every 10 minutes, but on iOS it's every 1 minute.

**Comment by mauron85** [comment]
This is not possible on iOS. Because of limitation of ios, it could be implemented in foreground mode only.

**Comment by IAmDragon** [comment]
@mauron85 I have this issue as well and your comment does absolutely nothing to help. Clearly it must work in some capacity because otherwise how do you implement background location tracking on iOS?

Right now in my app it's implemented in it gets the location every _single_ minute, and that uses about 35-40% of battery life in a day. 

There has to be a workaround, otherwise you might as well remove iOS from the package entirely with background location tracking.

**Comment by mauron85** [comment]
I'm sorry that this plugin didn't fulfil your expectations.

>There has to be a workaround, otherwise you might as well remove iOS from the package entirely with background location tracking.

One would expect some degree some degree of gratitude, but well let's keep this upon my consideration. OK?

The problem is iOS LocationProvider doesn't have timeouts. Some libraries are doing interval polling by setting timer. The problem is that timers don't fire when app is in background. So I don't want to spend time implementing something that actually I wont use. However if something implement this as separate location provider (as we have RAW, DISTANCE, ACTIVITY). I would merge it.

**Comment by IAmDragon** [comment]
Sorry, I don't mean to seem unappreciative it's just that this is one of the only working repo's  and I've hit a few roadblocks, with this being one of them.

If you were in my shoes what next step would you take? I'm trying to poll every 10 or 15 minutes, because that would use 10-15 times less battery than it currently is using (assuming it works like that)

I'll look into it more and see what I can dig up

**Comment by mauron85** [comment]
If I were in your shoes. First I would reconsider, if I just can't make it happen with existing solution (adjust my expectations). And if that's really hard requirement, that can't be changed, I would implement new LocationProvider. Later I would push PR to this repo so other can benefit too (describing all it's limitations). Also I don't recommend you to "outsmart" apple and do some crazy workaround, or it can end like https://github.com/mauron85/cordova-plugin-background-geolocation/issues/394 (not saying it's your case).

**Comment by chinmay-ksolves** [comment]
@mauron85 
This plugin is not working properly,
As my config looks like : 
let config = {

			desiredAccuracy: 0,
			stationaryRadius: 10,
			distanceFilter: 20,
			stopOnTerminate: false,
			startOnBoot: true,
			startForeground: true,
			locationProvider: 1,
			interval: 10000,
			fastestInterval: 5000,
			activitiesInterval: 10000,
			url: "https://.........",
			method: "POST",
			httpHeaders: {
				'content-type': 'application/json'
			},
			autoSync: true,
			maxDaysToPersist: 1,
			params: {
				latitude: '@latitude',
				longitude: '@longitude',
				username : global.nav_username,
				auth_key : global.nav_auth_key
			},
			notificationTitle: 'Background tracking',
			notificationText: 'enabled',  
			debug: true
		};

But it does not send the location to the server.
Although I have provided of 10000 milliseconds it updates the lat, long in 2-3 seconds.
If the device is at the stationary position then also it updates the location.
