### ISSUE TITLE
Question about syncThreshold and syncUrl

### ISSUE THREAD

**Issue by Tiagow** [mauron85/cordova-plugin-background-geolocation#402]
## Your Environment

* Plugin version: 3.0.0-alpha.18
* Platform: Android
* OS version: 8 
* Device manufacturer and model: Galaxy  #S8
* Cordova version (`cordova -v`): 7.1.0
* Cordova platform version (`cordova platform ls`): Android 6.3.0
* Plugin configuration options: 
* Link to your project:

## Context
First of all I would like to thank you for this plugin, it is amazing.
Regarding the management of fail post locations to the server, `syncThreshold` specifies "how many previously failed locations will be sent to server at once". And later in the doc it says "Locations are send only in single batch, when number of locations reaches `option.syncTreshold`.
Does this mean that if `syncThreshold` is set to 100, only after 100 failed post locations `syncUrl` will act and send the locations to my URL? If it is the case, can I set it to 5, for example, and expect it to send  to the server after 5 failed posts?

"When `option.syncUrl` is defined all failed to post locations will be coalesced and send in some time later". How does this "time later" works?

And finally, if I want to send the failed post locations manually, what should be the process? 
Can I use `getValidLocations()` and then `deleteLocation()` or `deleteAllLocations()` to "clear" `syncTreshold` list?

**Comment by mauron85** [comment]
>Does this mean that if syncThreshold is set to 100, only after 100 failed post locations syncUrl will act and send the locations to my URL?
yes

>If it is the case, can I set it to 5, for example, and expect it to send to the server after 5 failed posts?
yes, but also don't set `maxLocations` to very low number (default is 10000), because sync can miss some stored locations as they get overwritten after maxLocation is reached. This can happen when you set timeout for 1second and maxLocation to very low number. Plugin will try to send location via url first and if it fails the failed location will not "appear" in sync for at least 1 min. But due low maxLocation number in this 1 minute it can get overwritten by another location. Hopefully it makes sense.

>And finally, if I want to send the failed post locations manually, what should be the process?
Can I use getValidLocations() and then deleteLocation() or deleteAllLocations() to "clear" syncTreshold list?

Yes. But I see it myself as suboptimal as to not loose single locations you have to getValidLocations first, post them in you js function and then delete one by one. I don't recomment deleteAllLocations() because there will be some delay between call getValidLocations and deleteAllLocations and you may delete locations that didn't appeared in getValidLocations.
I think i introduce new method `forceSync` to cover this scenario in single step.

**Comment by Tiagow** [comment]
> Hopefully it makes sense. 

It does hahah

> I think i introduce new method forceSync to cover this scenario in single step.

That would be great.
What I want to do is when the user opens the app, verify if there is something in the `syncTreshold` list and then send it to the server right away.

**Comment by mauron85** [comment]
Server has to return http 200 or 201. For testing use this one https://github.com/mauron85/background-geolocation-server
