### ISSUE TITLE
Documentation v3 by default

### ISSUE THREAD

**Issue by bastiendonjon** [mauron85/cordova-plugin-background-geolocation#433]
Why v3 of the documentation is the default version, while your last release is v2.3.5 ?

It's confusing .. in my opinion

**Comment by mauron85** [comment]
The reason is I really want to encourage people to use and help test v3.
Taking into account that Plugin is free, having this feedback and
occasional donation is very valuable for me. If people only used stable
version, I probably stop releasing new versions as there will be no value
for me doing so. Hopefully it make sense. ;)

**Comment by mauron85** [comment]
on other hand, yes it bit confusing. But for example there is notice on very top, saying it's documentation for v3. ...

**Comment by bastiendonjon** [comment]
ok ;-)
