### ISSUE TITLE
Notification is never dismissed

### ISSUE THREAD

**Issue by Moventes** [mauron85/cordova-plugin-background-geolocation#465]
When I start the geolocation, a notification is displayed.
However, when I stop it, I would expect the notification to be dismissed, but it stays on as long as the application runs. I have to kill the application for the notification to disappear.

From My point of view, should I stop the service, the notification should be dismissed.

* Plugin version: 3.0.0-alpha.38
* Platform: Android
* OS version: 8
* Device manufacturer and model: HTC U11
* Cordova version (`cordova -v`):
* Cordova platform version (`cordova platform ls`): 6.3.0

**Comment by sunnymtl** [comment]
Same problem here! In my case, the notification can only be dismissed (by calling stop() ) when the app is in foreground.

**Comment by pedubreuil** [comment]
Any update about this issue?

**Comment by mauron85** [comment]
In recent versions there is option startForeground. If you set it to true, then notification will only be present when app is in background.

@sunnymtl configure plugin with stopOnTerminate: true. Then notification will be dismissed (also location tracking).

**Comment by YeisonVelez11** [comment]
@mauron85  @sunnymtl @pedubreuil  Is there any way to not show any type of notification? In fact, some messages appear when I move, I do not want the user to see them.

**Comment by mohpra** [comment]
@sunnymtl @pedubreuil @YeisonVelez11 

Check this out.

https://github.com/mauron85/cordova-plugin-background-geolocation/issues/455#issuecomment-449900311

**Comment by Fever905** [comment]
That grey toast message at the bottom is because you have debug: true or you specifically don't have debug: false in your main config.

Also in these make sure its false:

  BackgroundGeolocation.on('background', function() {
    console.log('[INFO] App is in background');
    // you can also reconfigure service (changes will be applied immediately)
    BackgroundGeolocation.configure({ debug: false });
  });

  BackgroundGeolocation.on('foreground', function() {
    console.log('[INFO] App is in foreground');
    BackgroundGeolocation.configure({ debug: false });
  });

As for removing the notification, I'm looking into that as well.  They say it's better to have it so android OS doesn't kill the process.   What you could do is change it to say something about the app.  Like SuperTextPlus is ready for your texts!  Problem is it never goes away.

Users wouldn't necessarily figure out that the app is tracking them (if you were looking to hide it for that reason)
