### ISSUE TITLE
Unable to import and use its functions

### ISSUE THREAD

**Issue by ShafiqShams** [mauron85/cordova-plugin-background-geolocation#513]
## Your Environment

* Plugin version: 3.0.0-alpha.47
* Platform: iOS
* OS version: macOS High Sierra version 10.13.6 (17G65)
* Device manufacturer and model: iPhone 6s version 11.4.1
* Running in Simulator: No
* Cordova version (cordova -v): 8.0.0
* Cordova platform version (cordova platform ls): ios 4.5.5
* Plugin configuration options: 
```
    <plugin name="cordova-plugin-mauron85-background-geolocation" spec="^3.0.0-alpha.47">
        <variable name="ALWAYS_USAGE_DESCRIPTION" value="This app always requires location tracking" />
        <variable name="MOTION_USAGE_DESCRIPTION" value="This app requires motion detection" />
    </plugin>
```

## Context

I have installed this plugin: cordova-plugin-mauron85-background-geolocation@alpha
and imported in my ionic application like:
import  BackgroundGeolocation  from "cordova-plugin-mauron85-background-geolocation";
but I am not able to use its functions, I this plugin is even exporting the functions, but I am unable to use.
I am not injecting this. I am just importing and using like the sample example, but still not working.

![screen shot 2018-11-15 at 4 13 33 pm](https://user-images.githubusercontent.com/24293253/48549394-7d322200-e8f1-11e8-9474-1676dd655eba.png)

## Expected Behavior
It should work properly and able to use all of its functions like configure, on etc..

## Actual Behavior
Methods are not reachable.

## Steps to Reproduce
Simply create a new application and install the plugin with these two commands:
cordova plugin add cordova-plugin-mauron85-background-geolocation@alpha

## Debug logs
Unable to build the app.

**Comment by allensutton** [comment]
@ShafiqEssani Are you using Angular by any chance?  I'm having the same issue and I've been searching for two days for a solution.  Initially I thought it was because 2.x is installed by default, but even after correcting it by removing 2.x and installing 3.0, I have the same problem where Visual Studio Code is giving me an error saying that it can't find BackgroundGeolocation.  When I add cordova.plugins.BackgroundGeolocation instead, it compiles fine, but when I am debugging with an emulator, I get the error: "ERROR Error: Uncaught (in promise): TypeError: Cannot read property 'BackgroundGeolocation' of undefined" so that's not the solution I assume.  For the record, Cordova shows that I am in fact running 3.0:

`cordova-plugin-device 2.0.2 "Device"
cordova-plugin-geolocation 4.0.1 "Geolocation"
cordova-plugin-mauron85-background-geolocation 3.0.0-alpha.47 "CDVBackgroundGeolocation"
cordova-plugin-whitelist 1.3.3 "Whitelist"
`

**Comment by ShafiqEssani** [comment]
Hey @allensutton thanks for commenting.
Let me explain you whats going wrong.
I am building an Ionic application, in which I want to track users location in background. For this purpose, I used cordova plugin of background mode using this command 
`cordova plugin add cordova-plugin-mauron85-background-geolocation@alpha`

Next I import this plugin using this line:
import { BackgroundGeolocation } from "cordova-plugin-mauron85-background-geolocation";
I am NOT getting the error of cannot find module.
Its imported without any error but but but when I am using its member functions like 

```
BackgroundGeolocation.configure({
    locationProvider: BackgroundGeolocation.ACTIVITY_PROVIDER,
    desiredAccuracy: BackgroundGeolocation.HIGH_ACCURACY,
    stationaryRadius: 50,
    distanceFilter: 50,
    notificationTitle: 'Background tracking',
    notificationText: 'enabled',
    debug: true,
    interval: 10000,
    fastestInterval: 5000,
    activitiesInterval: 10000,
    url: 'http://192.168.81.15:3000/location',
    httpHeaders: {
      'X-FOO': 'bar'
    },
    // customize post properties
    postTemplate: {
      lat: '@latitude',
      lon: '@longitude',
      foo: 'bar' // you can also add your own properties
    }
  });

  BackgroundGeolocation.on('stationary', function(stationaryLocation) {
    // handle stationary locations here
  });

  BackgroundGeolocation.on('error', function(error) {
    console.log('[ERROR] BackgroundGeolocation error:', error.code, error.message);
  });

  BackgroundGeolocation.on('start', function() {
    console.log('[INFO] BackgroundGeolocation service has been started');
  });

  BackgroundGeolocation.on('stop', function() {
    console.log('[INFO] BackgroundGeolocation service has been stopped');
  });
```

I AM UNABLE TO BUILD MY IONIC PROJECT.
Thats the problem where I cntrl click on the functions ( configure, on etc ) I wont be able to navigate to the plugin file.

The screenshot posted in the question says it all.
I have tried it with both of the import statements but its not working.
Any help bro?

**Comment by allensutton** [comment]
That sounds a lot like my previous issue.  If you issue the command:
`cordova plugin ls`
...what does it show?  I had the same problem earlier and it was because the "cordova plugin add cordova-plugin-mauron85-background-geolocation" command installs version 2.3.5 by default.  The 2.x version of this plugin uses a file called "backgroundGeolocation.js" whereas in the new 3.x version, the file is called "BackgroundGeolocation.js" and there is a TypeScript file called "BackgroundGeolocation.d.ts" as well.  Once I upgraded the plugin with "cordova plugin add cordova-plugin-mauron85-background-geolocation@latest" that issue was resolved because the case for the import statement then matched the case of the actual file name.

**Comment by dvdpzzt-webmapp** [comment]
Hi. I have the same problem right now in ionic 4. I installed the plugin following the [ionic-native documentation](https://ionicframework.com/docs/native/background-geolocation). The plugin installs successfully and I can see the version 3.0.0-alpha.50 installed. As @ShafiqShams I can import everything but I cannot use the method linked to BackgroundGeolocation as configure() or anything else. Since some time has passed, have you found anything yet?

**Comment by dvdpzzt-webmapp** [comment]
Turns out that the documentation I followed it' wrong, at least for ionic 4. I just made it works by following the real [ionic-native documentation](https://ionicframework.com/docs/native/#usage-with-angular-apps). I basically was missing the declaration in the `app.module.ts` and that I have to import from `@ionic-native/background-geolocation/ngx` with the final `/ngx`

**Comment by ShafiqShams** [comment]
Actually, I am working with Ionic version 3.20.0 and its working without /ngx.
Do I need to give it a shot?

**Comment by dvdpzzt-webmapp** [comment]
Well, the documentation I linked is the ionic v4 one, so I don't know about the v3 as I never used it. Anyway, I think that the more important part of what I said was the missing declaration here

> I basically was missing the declaration in the `app.module.ts`
