### ISSUE TITLE
Not working under Android 9

### ISSUE THREAD

**Issue by sebastian-negoro** [mauron85/cordova-plugin-background-geolocation#609]
## Your Environment

* Plugin version: 3.0.3
* Platform: Android
* OS version: 9
* Device manufacturer and model: Honor 9 Lite

* Running in Simulator:
* Cordova version (`cordova -v`):
* Cordova platform version (`cordova platform ls`):
* Plugin configuration options: 
* Link to your project:

## Context
I have an existing mobile app with this plugin. It worked correctly on my device under Android 8, however, after upgrading to Android 9, I've noticed that all app connections, including background geolocation, are killed after 5-7 minutes in background (I also have a WebSocket connection in my app). I think it's because of Android 9. Any suggestions?

## Expected Behavior
App should work in background

## Actual Behavior
Probably, the OS closes connections after 5-7 minutes of background mode

## Steps to Reproduce

1.
2.
3.
4.

**Comment by evelim** [comment]
I have the. same problem: Caused by: java.lang.ClassNotFoundException: Didn't find class "android.support.v4.content.ContextCompat" 
--------- beginning of crash
08-02 06:28:28.394 16637 16897 E AndroidRuntime: FATAL EXCEPTION: pool-9-thread-2
08-02 06:28:28.394 16637 16897 E AndroidRuntime: Process: xx, PID: 16637
08-02 06:28:28.394 16637 16897 E AndroidRuntime: java.lang.NoClassDefFoundError: Failed resolution of: Landroid/support/v4/content/ContextCompat;
08-02 06:28:28.394 16637 16897 E AndroidRuntime: 	at com.intentfilter.androidpermissions.PermissionManager.permissionAlreadyGranted(PermissionManager.java:82)
08-02 06:28:28.394 16637 16897 E AndroidRuntime: 	at com.intentfilter.androidpermissions.PermissionHandler.filterGrantedPermissions(PermissionHandler.java:132)
08-02 06:28:28.394 16637 16897 E AndroidRuntime: 	at com.intentfilter.androidpermissions.PermissionHandler.checkPermissions(PermissionHandler.java:38)
08-02 06:28:28.394 16637 16897 E AndroidRuntime: 	at com.intentfilter.androidpermissions.PermissionManager.checkPermissions(PermissionManager.java:50)
08-02 06:28:28.394 16637 16897 E AndroidRuntime: 	at com.marianhello.bgloc.BackgroundGeolocationFacade.start(BackgroundGeolocationFacade.java:217)
08-02 06:28:28.394 16637 16897 E AndroidRuntime: 	at com.tenforwardconsulting.bgloc.cordova.BackgroundGeolocationPlugin.start(BackgroundGeolocationPlugin.java:355)
08-02 06:28:28.394 16637 16897 E AndroidRuntime: 	at com.tenforwardconsulting.bgloc.cordova.BackgroundGeolocationPlugin.access$000(BackgroundGeolocationPlugin.java:37)
08-02 06:28:28.394 16637 16897 E AndroidRuntime: 	at com.tenforwardconsulting.bgloc.cordova.BackgroundGeolocationPlugin$1.run(BackgroundGeolocationPlugin.java:149)
08-02 06:28:28.394 16637 16897 E AndroidRuntime: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
08-02 06:28:28.394 16637 16897 E AndroidRuntime: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
08-02 06:28:28.394 16637 16897 E AndroidRuntime: 	at java.lang.Thread.run(Thread.java:764)
08-02 06:28:28.394 16637 16897 E AndroidRuntime: Caused by: java.lang.ClassNotFoundException: Didn't find class "android.support.v4.content.ContextCompat" on path: DexPathList[[zip file "/data/app/br.com.evelim.fretes-UTzeS6b4NN90DPn6PkN_sA==/base.apk"],nativeLibraryDirectories=[/data/app/br.com.evelim.fretes-UTzeS6b4NN90DPn6PkN_sA==/lib/arm, /system/lib, /system/vendor/lib]]
08-02 06:28:28.394 16637 16897 E AndroidRuntime: 	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:125)
08-02 06:28:28.394 16637 16897 E AndroidRuntime: 	at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
08-02 06:28:28.394 16637 16897 E AndroidRuntime: 	at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
08-02 06:28:28.394 16637 16897 E AndroidRuntime: 	... 11 more
08-02 06:28:28.398 16637 16897 E com.marianhello.logging.UncaughtExceptionLogger: FATAL EXCEPTION: pool-9-thread-2java.lang.NoClassDefFoundError: Failed resolution of: Landroid/support/v4/content/ContextCompat;
08-02 06:28:28.398 16637 16897 E com.marianhello.logging.UncaughtExceptionLogger: 	at com.intentfilter.androidpermissions.PermissionManager.permissionAlreadyGranted(PermissionManager.java:82)
08-02 06:28:28.398 16637 16897 E com.marianhello.logging.UncaughtExceptionLogger: 	at com.intentfilter.androidpermissions.PermissionHandler.filterGrantedPermissions(PermissionHandler.java:132)
08-02 06:28:28.398 16637 16897 E com.marianhello.logging.UncaughtExceptionLogger: 	at com.intentfilter.androidpermissions.PermissionHandler.checkPermissions(PermissionHandler.java:38)
08-02 06:28:28.398 16637 16897 E com.marianhello.logging.UncaughtExceptionLogger: 	at com.intentfilter.androidpermissions.PermissionManager.checkPermissions(PermissionManager.java:50)
08-02 06:28:28.398 16637 16897 E com.marianhello.logging.UncaughtExceptionLogger: 	at com.marianhello.bgloc.BackgroundGeolocationFacade.start(BackgroundGeolocationFacade.java:217)
08-02 06:28:28.398 16637 16897 E com.marianhello.logging.UncaughtExceptionLogger: 	at com.tenforwardconsulting.bgloc.cordova.BackgroundGeolocationPlugin.start(BackgroundGeolocationPlugin.java:355)
08-02 06:28:28.398 16637 16897 E com.marianhello.logging.UncaughtExceptionLogger: 	at com.tenforwardconsulting.bgloc.cordova.BackgroundGeolocationPlugin.access$000(BackgroundGeolocationPlugin.java:37)
08-02 06:28:28.398 16637 16897 E com.marianhello.logging.UncaughtExceptionLogger: 	at com.tenforwardconsulting.bgloc.cordova.BackgroundGeolocationPlugin$1.run(BackgroundGeolocationPlugin.java:149)
08-02 06:28:28.398 16637 16897 E com.marianhello.logging.UncaughtExceptionLogger: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
08-02 06:28:28.398 16637 16897 E com.marianhello.logging.UncaughtExceptionLogger: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
08-02 06:28:28.398 16637 16897 E com.marianhello.logging.UncaughtExceptionLogger: 	at java.lang.Thread.run(Thread.java:764)
08-02 06:28:28.398 16637 16897 E com.marianhello.logging.UncaughtExceptionLogger: Caused by: java.lang.ClassNotFoundException: Didn't find class "android.support.v4.content.ContextCompat" on path: DexPathList[[zip file "/data/app/br.com.evelim.fretes-UTzeS6b4NN90DPn6PkN_sA==/base.apk"],nativeLibraryDirectories=[/data/app/br.com.evelim.fretes-UTzeS6b4NN90DPn6PkN_sA==/lib/arm, /system/lib, /system/vendor/lib]]
08-02 06:28:28.398 16637 16897 E com.marianhello.logging.UncaughtExceptionLogger: 	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:125)
08-02 06:28:28.398 16637 16897 E com.marianhello.logging.UncaughtExceptionLogger: 	at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
08-02 06:28:28.398 16637 16897 E com.marianhello.logging.UncaughtExceptionLogger: 	at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
08-02 06:28:28.398 16637 16897 E com.marianhello.logging.UncaughtExceptionLogger: 	... 11 common frames omitted

**Comment by jffs** [comment]
same problem
