### ISSUE TITLE
Foreground tracking not reliable?

### ISSUE THREAD

**Issue by brudidier** [mauron85/cordova-plugin-background-geolocation#63]
Hi there!

I am experiencing some issues with your awesome plugin (thanks again for your contribution)
FYI I edited it in order to remove the stationary filter and co, as I didn't need it.

Here is what I've noticed based on my test and other users feedback: 
Geolocation when the app is in background, both Android and iOS is working great BUT, it seems like when the app is in foreground even though I can see **the arrow** on iOS or the **Background notification** on Android, i HAVE to go to the background and then to foreground again in order for the app to send positions to the server.
If I don't toggle the background/foreground mode, it seems like it's running, but not sending any position.
Any idea of what could be happening?

Worst case, could I just start the plugin when the app goes to background and use navigator.watchPosition in foreground? How would I do this and avoid the plugin + HTML5 geoloc to run at the same time?

Thanks a lot!

**Comment by uzumakinaruto123** [comment]
how are you sending the location updates? http ? 

By any chance is your http post wrapped inside some cordova plugin ? I am not sure if its the same case for you but this is what my observation was :- 

In foreground :- 

1. location updates are received ,Callback function fires successfuly
2. Your location update will also succeed even if inside any cordova plugin since device is in ready state.

Now in background :- 

1. location updates are received ,Callback function fires successfuly
2. If app in background,
       - this plugin always runs correctly , now it will try posting data
       - but now if you have some cordova plugin used in callback or any such plugin which requires device to be ready , will not work.
      
3.  As soon as you resume the app now in foreground , device gets ready and hence plugins are ready , now it proceeds further.



For this you need to do pure http call inside callback function without any plugin based implementation. I am not sure about but i think even localstorage wont work here.
Check this :- https://github.com/mauron85/cordova-plugin-background-geolocation/issues/44

**Comment by megadrazz** [comment]
The plugin and really impressive !!!
I send latitude and longitude for http with parameters in promeiro plan and successfully background !!!!! thanks in advance

**Comment by brudidier** [comment]
Thanks @uzumakinaruto123!
My http post is done trough a javascript service, but no Cordova plugin. The app is wrapped up with Cordova though.

It actually feels like, it has to go through the background mode to work, but the foreground mode doesn't seem to be constantly working not the opposite. 
So to be clearer, background works great, but foreground send back some random positons. Also, we did remove the stationary filter in Native code, but is it hidden somewhere in javascript that will be only run in Foreground maybe?

While in foreground, we do run a getCurrentLocation every 7sec on top of this plugin. Would that conflict with it in any way? 

Thanks again!

**Comment by uzumakinaruto123** [comment]
I can't answer your first quesion but checking some logs might help. about second question getCurrentPosition won't affect the plugin in any way it won't conflict. maybe mauron can help you

**Comment by megadrazz** [comment]
I'm using Angle js follow an example
var params = {latetude: lat, longetude: lng};
.controller("Background" , function($scope,$http){
 $http({
            method: "GET",
            url: "http://www.site/a1/a2.php", params
                  }).then(function(data){
                        $scope.news = data.data;
                  })
}
It works perfect in both android and iso,
in the foreground and background

**Comment by mauron85** [comment]
This was standartd behaviour of former plugin I have forked -> to work only as background service and turn self off when it foreground. This was changed in 2.0.0. So now it should work also in foreground, both on iOS and Android
