### ISSUE TITLE
Http requests doesn't work in background

### ISSUE THREAD

**Issue by Taxi4you** [mauron85/cordova-plugin-background-geolocation#644]
It seems that the plugins success to find position even on background and even when screen is locked (Android device - Samsung Galaxy S7). But HTTP requests using Axios are not getting sent after 4-5 minutes.

Is there any fix for this?

**Comment by ekohadim** [comment]
I had the same issue, i used Fetch (native javascript) to do the http post. And found some advice to use this cordova-plugin-advanced-http. And it works, i have been testing it, but so far okay.

**Comment by vrdriver** [comment]
I have the same problem for my Huawei Mate 20 Pro with power management set to manual. I'm doing my own POST method instead of the built in one. @ekohadim, how has your mentioned change gone? Has it worked past the 5mins? The funny this is after the phone wakes up, it then starts POSTing the data again, as per my question here and so catches up on the geolocation. It takes an app that is real time in to a delayed realtime, so it sort of doesn't work as it should. 
https://forum.ionicframework.com/t/httpclient-infinity-timeout/183413/2
