### ISSUE TITLE
 Issue with compiling the app for android

### ISSUE THREAD

**Issue by Mihaildimitrov** [mauron85/cordova-plugin-background-geolocation#666]
Hello everyone I need HELP with one issue.

I built one clean Phonegap Application only with this plugin and everything work as expected. 
But when I add the plugin to my project I am not able to build the application.
There is some conflict with one of my plugins(phonegap-plugin-push).

## Your Environment

* Plugin version: ~3.1.0
* Platform: Android
* Other plugins:
- Plugin: phonegap-plugin-push
- version:  ^2.2.3

* Running in Simulator: NO

## Context

When I add both plugins "Phonegap-plugin-push" and "cordova-plugin-background-geolocation"
I got an error when try to build an APK.

ERROR:
**com.android.dex.DexException: Multiple dex files define** .... 

Seems that the plugin use some deprecated methods and "Phonegap-plugin-push" detects and trigger this issue.

## Expected Behavior

To build successfully for specific platform.

## Actual Behavior

Got error during the building process.

## Steps to Reproduce

1. Create one phonegap application
2. Add both plugins "Phonegap-plugin-push" and "cordova-plugin-background-geolocation"
3. Add android platform
4. Build APK

## Debug logs

**com.android.dex.DexException: Multiple dex files define** .... 

Thanks in advance!

**Comment by hohler** [comment]
which file is specified in "multiple dex files define..."?

I had a similar issue and the problem was, that another plugin related the commons-io:2.4 library the right way (with graddle).
This plugin here is copying some files of the commons-io library directly to the src folder in platforms/android. That's a bad way. It should rather relate the files through the library as dependency in the graddle file.
