### ISSUE TITLE
[Question]: On iOS do we need to add location in UIBackgroundModes Key?

### ISSUE THREAD

**Issue by gaurav-chandra** [mauron85/cordova-plugin-background-geolocation#674]
Great plugin. Thanks for that. I recently got a rejection reason from Apple that location is added in UIBackgroundModes Key but my app does not actively use it. They so not event start using it during testing.

So, my question is: do we need to add location in UIBackgroundModes Key?

**Comment by anujraghuvanshi** [comment]
Yes @gaurav-chandra - If you use Background mode with location, You need to define that your app is using location services in background. Otherwise if apple finds code related this and incase you haven't given location in UIBackgroundModes, Apple may reject this. 

Including this, There may be another reasons of rejection of app by Apple. Thanks!
