### ISSUE TITLE
Comparison to transistorsoft / cordova-background-geolocation-lt

### ISSUE THREAD

**Issue by jacobg** [mauron85/cordova-plugin-background-geolocation#679]
Has anyone used `transistorsoft / cordova-background-geolocation-lt` plugin, and can offer feedback on their experience with it, in comparison to this plugin? Obviously, this plugin is free, and the other one is commercially licensed. But I'm hoping for more technical information about quality, development ergonomics, vendor support, and functionality.

Sorry if I'm violating norms by posting a discussion thread as an issue. I'm just not sure where to initiate such as conversation with developers who actually use this plugin.

**Comment by behindraven** [comment]
Hi jacobg,

I am also interested in Transistorsoft's plugin because mauron85's doesn't work as my expected. if moving to Tansistorsoft i will share my experiences. Only foreground/background location access is my needed. Some other features such as storing locations in to local db and sending location to url are not my required.

**Comment by HarelM** [comment]
I have tried to use both and I ended up using this one.
I've seen accuracy issues with the other one due to the battery philosophy.
See my issue here:
https://github.com/transistorsoft/cordova-background-geolocation-lt/issues/980
The service is good and I got a response to every issue I raised but I prefer accuracy over battery usage and ended up using this plugin.
